import { ToolLayout } from '../components/common/ToolLayout';
import { QRGenerator } from '../components/tools/qr-generator/QRGenerator';

const seoMeta = {
  title: 'QR Code Generator - Free Custom QR Code Maker Online | Web Tools Suite',
  description:
    'Generate QR codes for free with custom colors, logos, and styles. Create QR codes for URLs, text, WiFi, vCard contacts, email, and phone numbers. Download as PNG, SVG, or JPEG.',
  keywords: [
    'qr code generator',
    'create qr code',
    'qr code maker',
    'free qr code',
    'custom qr code',
    'qr code with logo',
    'wifi qr code',
    'url qr code',
    'vcard qr code',
    'qr code creator',
    'qr code design',
    'contact qr code',
    'email qr code',
    'phone qr code',
  ],
  canonicalUrl: 'https://webtools.suite/qr-generator',
};

const howToUseSteps = [
  'Select the type of QR code you want to create: URL, Text, Email, Phone, WiFi, or vCard contact.',
  'Enter the content for your QR code in the appropriate input fields.',
  'Your QR code will be generated automatically and displayed in the preview area.',
  'Click "Advanced Options" to customize the QR code appearance - adjust size, colors, and error correction level.',
  'Optionally upload a logo image to display in the center of your QR code.',
  'Download your QR code in your preferred format: PNG for web use, SVG for print, or JPEG for compatibility.',
  'Use the copy button to copy the QR code image directly to your clipboard.',
  'Share the tool with others using the social share buttons.',
];

const faqs = [
  {
    question: 'What can I create QR codes for?',
    answer:
      'You can create QR codes for URLs (website links), plain text messages, email addresses with optional subject and body, phone numbers, WiFi network credentials (network name, password, and encryption type), and vCard contact information including name, organization, phone, email, website, and address.',
  },
  {
    question: 'Can I customize the appearance of my QR code?',
    answer:
      'Yes, you can fully customize your QR code. Change the foreground and background colors to match your brand, adjust the size from 100px to 1000px, set the error correction level, and even add a logo or image in the center. Higher error correction levels allow for more customization while maintaining scannability.',
  },
  {
    question: 'What is error correction and why does it matter?',
    answer:
      'Error correction allows QR codes to be read even when partially damaged or obscured. Low (L) offers 7% error correction with the smallest code size. Medium (M) offers 15% correction with a good balance. Quartile (Q) offers 25% correction for higher reliability. High (H) offers 30% correction, which is best when adding logos as they cover part of the code.',
  },
  {
    question: 'What format should I download my QR code in?',
    answer:
      'PNG is ideal for web use, social media, and digital documents - it offers good quality at reasonable file sizes. SVG is best for print materials as it can scale to any size without losing quality. JPEG offers maximum compatibility but may have slight quality loss due to compression.',
  },
  {
    question: 'Can I add my logo to the QR code?',
    answer:
      'Yes, you can upload any image to display in the center of your QR code. For best results, use High error correction level when adding a logo, as the logo covers part of the code data. Keep your logo relatively small compared to the QR code, and ensure high contrast between the logo and QR code colors.',
  },
  {
    question: 'Do QR codes expire?',
    answer:
      'Static QR codes like those generated by our tool never expire. They encode the information directly into the pattern and will work forever as long as the linked content (like a website URL) remains available. Dynamic QR codes from paid services can expire or be changed, but static codes are permanent.',
  },
  {
    question: 'Is my data safe when creating QR codes?',
    answer:
      'Yes, completely. All QR code generation happens locally in your browser. Your data (URLs, WiFi passwords, contact information) is never sent to any server. When you close the page, all data is cleared. This is especially important for WiFi QR codes containing network passwords.',
  },
  {
    question: 'Why is my QR code not scanning properly?',
    answer:
      'Common scanning issues include: low contrast between foreground and background colors (use dark on light), QR code too small when printed, error correction level too low when using a logo, or damaged/blurry print. Try increasing size, using standard black and white colors, or increasing error correction level.',
  },
];

const relatedTools = [
  {
    name: 'Password Generator',
    href: '/password-generator',
    description: 'Create strong, secure passwords instantly',
  },
  {
    name: 'Text Case Converter',
    href: '/text-case-converter',
    description: 'Convert text between different cases',
  },
  {
    name: 'JSON Formatter',
    href: '/json-formatter',
    description: 'Format, validate, and beautify JSON data',
  },
  {
    name: 'Color Picker',
    href: '/color-picker',
    description: 'Pick and convert colors between formats',
  },
  {
    name: 'Image Compressor',
    href: '/image-compressor',
    description: 'Compress images without losing quality',
  },
  {
    name: 'Invoice Generator',
    href: '/invoice-generator',
    description: 'Create professional invoices instantly',
  },
];

const seoDescription = `
QR codes have become an essential tool for bridging the physical and digital worlds. These two-dimensional barcodes can store a variety of information and be scanned instantly by any smartphone camera, making them perfect for sharing URLs, contact information, WiFi credentials, and more.

Our free online QR Code Generator creates high-quality, customizable QR codes directly in your browser. Whether you need a simple URL code for your business card or a branded QR code with your logo for marketing materials, our tool provides everything you need without requiring signup or payment.

Understanding QR Code Types

URL QR codes are the most common type, linking directly to websites. When scanned, they open the web browser and navigate to your specified URL. Perfect for business cards, flyers, product packaging, and advertisements where you want to drive traffic to your website.

Text QR codes can contain any plain text message up to several thousand characters. While less common, they are useful for displaying information that does not require internet access, like instructions, poems, or messages.

Email QR codes create a mailto link that opens the user's email client with pre-filled recipient address, subject line, and body text. Ideal for feedback forms, contact requests, or any situation where you want to make it easy for someone to email you.

Phone QR codes contain a tel link that initiates a phone call when scanned. Perfect for customer service numbers on products, contact information on business cards, or anywhere you want to enable one-tap calling.

WiFi QR codes encode your network credentials, allowing guests to connect to your WiFi by simply scanning the code. This eliminates the need to share complex passwords verbally. The code can include network name (SSID), password, encryption type (WPA/WPA2, WEP, or none), and hidden network status.

vCard QR codes contain complete contact information in a standardized format. When scanned, they allow the user to add the contact directly to their phone's address book. Include name, organization, job title, email, phone, website, and address.

Customization Options

Our generator offers extensive customization to match your brand and use case. Size can be adjusted from 100 to 1000 pixels, suitable for everything from small web icons to large print materials.

Colors can be fully customized for both the QR code pattern (foreground) and background. While classic black on white offers the best scanning reliability, you can use any high-contrast color combination that matches your brand. Avoid light foreground colors on light backgrounds or dark on dark.

Error correction is a crucial setting that determines how much of the QR code can be damaged or obscured while still remaining scannable. Low (L) allows 7% damage and produces the smallest codes. Medium (M) allows 15% and is good for general use. Quartile (Q) allows 25% for higher reliability. High (H) allows 30% damage and is essential when adding logos.

Logo integration allows you to place an image in the center of your QR code, perfect for branding. The logo effectively covers part of the code's data, which is why high error correction is recommended. Keep logos simple and centered for best results.

Technical Specifications

QR codes use Reed-Solomon error correction, allowing them to be read even when partially obscured. Our generator supports all standard QR code versions, automatically selecting the appropriate version based on your content length and error correction level.

The generated codes follow international standards (ISO/IEC 18004) ensuring compatibility with all QR code readers. We use the qrcode library for generation, producing clean, pixel-perfect codes.

Output formats include PNG (best for digital use), SVG (best for print, infinitely scalable), and JPEG (maximum compatibility). SVG files are particularly valuable for print materials as they can be scaled to any size without quality loss.

Privacy and Security

All QR code generation happens locally in your browser using JavaScript. Your data - including WiFi passwords and contact information - is never transmitted to any server. This is especially important for WiFi QR codes, which contain your network password in plain text.

When you close the page, all entered data and generated codes are cleared from memory. We cannot access, view, or store any information you enter into the generator.

Best Practices for QR Codes

For print materials, ensure adequate size (minimum 2cm x 2cm for reliable scanning), sufficient quiet zone (white space around the code), and high contrast printing. Test scanning from the actual printed material before large print runs.

For digital use, consider the context where the code will be scanned. Users cannot scan a QR code displayed on the same device they are using, so QR codes in mobile apps or mobile websites are less useful than on desktop displays or print materials.

Always test your QR codes after creation by scanning them with multiple devices and QR reader apps. Include a short URL or fallback text near the code for users who cannot or prefer not to scan.
`.trim();

export function QRGeneratorPage() {
  return (
    <ToolLayout
      seo={seoMeta}
      title="QR Code Generator"
      description={seoDescription}
      howToUse={howToUseSteps}
      faqs={faqs}
      relatedTools={relatedTools}
      privacyNote="All processing happens locally in your browser"
    >
      <QRGenerator />
    </ToolLayout>
  );
}

export default QRGeneratorPage;
